/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ThemesIndexRouteImport } from './routes/themes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as QuestionBankIndexRouteImport } from './routes/question-bank/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CategorysIndexRouteImport } from './routes/categorys/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignOutIndexRouteImport } from './routes/(auth)/sign-out/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankIndexRoute = QuestionBankIndexRouteImport.update({
  id: '/question-bank/',
  path: '/question-bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorysIndexRoute = CategorysIndexRouteImport.update({
  id: '/categorys/',
  path: '/categorys/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignOutIndexRoute = authSignOutIndexRouteImport.update({
  id: '/(auth)/sign-out/',
  path: '/sign-out/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/categorys': typeof CategorysIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/question-bank': typeof QuestionBankIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/themes': typeof ThemesIndexRoute
  '/users': typeof UsersIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-out': typeof authSignOutIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/categorys': typeof CategorysIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/question-bank': typeof QuestionBankIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/themes': typeof ThemesIndexRoute
  '/users': typeof UsersIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-out': typeof authSignOutIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/categorys/': typeof CategorysIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/question-bank/': typeof QuestionBankIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-out/': typeof authSignOutIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/categorys'
    | '/dashboard'
    | '/question-bank'
    | '/questions'
    | '/quizzes'
    | '/settings'
    | '/themes'
    | '/users'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/categorys'
    | '/dashboard'
    | '/question-bank'
    | '/questions'
    | '/quizzes'
    | '/settings'
    | '/themes'
    | '/users'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/calendar/'
    | '/categorys/'
    | '/dashboard/'
    | '/question-bank/'
    | '/questions/'
    | '/quizzes/'
    | '/settings/'
    | '/themes/'
    | '/users/'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-out/'
    | '/(auth)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CategorysIndexRoute: typeof CategorysIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  QuestionBankIndexRoute: typeof QuestionBankIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignOutIndexRoute: typeof authSignOutIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank/': {
      id: '/question-bank/'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorys/': {
      id: '/categorys/'
      path: '/categorys'
      fullPath: '/categorys'
      preLoaderRoute: typeof CategorysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-out/': {
      id: '/(auth)/sign-out/'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof authSignOutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CategorysIndexRoute: CategorysIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  QuestionBankIndexRoute: QuestionBankIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ThemesIndexRoute: ThemesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignOutIndexRoute: authSignOutIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
