/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellUsersIndexRouteImport } from './routes/_shell/users/index'
import { Route as ShellThemesIndexRouteImport } from './routes/_shell/themes/index'
import { Route as ShellSubthemesIndexRouteImport } from './routes/_shell/subthemes/index'
import { Route as ShellQuizzesIndexRouteImport } from './routes/_shell/quizzes/index'
import { Route as ShellQuestionsIndexRouteImport } from './routes/_shell/questions/index'
import { Route as ShellQuestionBankIndexRouteImport } from './routes/_shell/question-bank/index'
import { Route as ShellProfileIndexRouteImport } from './routes/_shell/profile/index'
import { Route as ShellDashboardIndexRouteImport } from './routes/_shell/dashboard/index'
import { Route as ShellCategorysIndexRouteImport } from './routes/_shell/categorys/index'
import { Route as ShellCalendarIndexRouteImport } from './routes/_shell/calendar/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignOutIndexRouteImport } from './routes/(auth)/sign-out/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'

const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellUsersIndexRoute = ShellUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellThemesIndexRoute = ShellThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellSubthemesIndexRoute = ShellSubthemesIndexRouteImport.update({
  id: '/subthemes/',
  path: '/subthemes/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellQuizzesIndexRoute = ShellQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellQuestionsIndexRoute = ShellQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellQuestionBankIndexRoute = ShellQuestionBankIndexRouteImport.update({
  id: '/question-bank/',
  path: '/question-bank/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellProfileIndexRoute = ShellProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellDashboardIndexRoute = ShellDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellCategorysIndexRoute = ShellCategorysIndexRouteImport.update({
  id: '/categorys/',
  path: '/categorys/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellCalendarIndexRoute = ShellCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignOutIndexRoute = authSignOutIndexRouteImport.update({
  id: '/(auth)/sign-out/',
  path: '/sign-out/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-out': typeof authSignOutIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/calendar': typeof ShellCalendarIndexRoute
  '/categorys': typeof ShellCategorysIndexRoute
  '/dashboard': typeof ShellDashboardIndexRoute
  '/profile': typeof ShellProfileIndexRoute
  '/question-bank': typeof ShellQuestionBankIndexRoute
  '/questions': typeof ShellQuestionsIndexRoute
  '/quizzes': typeof ShellQuizzesIndexRoute
  '/subthemes': typeof ShellSubthemesIndexRoute
  '/themes': typeof ShellThemesIndexRoute
  '/users': typeof ShellUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-out': typeof authSignOutIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/calendar': typeof ShellCalendarIndexRoute
  '/categorys': typeof ShellCategorysIndexRoute
  '/dashboard': typeof ShellDashboardIndexRoute
  '/profile': typeof ShellProfileIndexRoute
  '/question-bank': typeof ShellQuestionBankIndexRoute
  '/questions': typeof ShellQuestionsIndexRoute
  '/quizzes': typeof ShellQuizzesIndexRoute
  '/subthemes': typeof ShellSubthemesIndexRoute
  '/themes': typeof ShellThemesIndexRoute
  '/users': typeof ShellUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteRouteWithChildren
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-out/': typeof authSignOutIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/_shell/calendar/': typeof ShellCalendarIndexRoute
  '/_shell/categorys/': typeof ShellCategorysIndexRoute
  '/_shell/dashboard/': typeof ShellDashboardIndexRoute
  '/_shell/profile/': typeof ShellProfileIndexRoute
  '/_shell/question-bank/': typeof ShellQuestionBankIndexRoute
  '/_shell/questions/': typeof ShellQuestionsIndexRoute
  '/_shell/quizzes/': typeof ShellQuizzesIndexRoute
  '/_shell/subthemes/': typeof ShellSubthemesIndexRoute
  '/_shell/themes/': typeof ShellThemesIndexRoute
  '/_shell/users/': typeof ShellUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/calendar'
    | '/categorys'
    | '/dashboard'
    | '/profile'
    | '/question-bank'
    | '/questions'
    | '/quizzes'
    | '/subthemes'
    | '/themes'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/calendar'
    | '/categorys'
    | '/dashboard'
    | '/profile'
    | '/question-bank'
    | '/questions'
    | '/quizzes'
    | '/subthemes'
    | '/themes'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-out/'
    | '/(auth)/sign-up/'
    | '/_shell/calendar/'
    | '/_shell/categorys/'
    | '/_shell/dashboard/'
    | '/_shell/profile/'
    | '/_shell/question-bank/'
    | '/_shell/questions/'
    | '/_shell/quizzes/'
    | '/_shell/subthemes/'
    | '/_shell/themes/'
    | '/_shell/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignOutIndexRoute: typeof authSignOutIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/users/': {
      id: '/_shell/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/themes/': {
      id: '/_shell/themes/'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ShellThemesIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/subthemes/': {
      id: '/_shell/subthemes/'
      path: '/subthemes'
      fullPath: '/subthemes'
      preLoaderRoute: typeof ShellSubthemesIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/quizzes/': {
      id: '/_shell/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof ShellQuizzesIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/questions/': {
      id: '/_shell/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof ShellQuestionsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/question-bank/': {
      id: '/_shell/question-bank/'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof ShellQuestionBankIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/profile/': {
      id: '/_shell/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/dashboard/': {
      id: '/_shell/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/categorys/': {
      id: '/_shell/categorys/'
      path: '/categorys'
      fullPath: '/categorys'
      preLoaderRoute: typeof ShellCategorysIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/calendar/': {
      id: '/_shell/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ShellCalendarIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-out/': {
      id: '/(auth)/sign-out/'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof authSignOutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteRouteChildren {
  ShellCalendarIndexRoute: typeof ShellCalendarIndexRoute
  ShellCategorysIndexRoute: typeof ShellCategorysIndexRoute
  ShellDashboardIndexRoute: typeof ShellDashboardIndexRoute
  ShellProfileIndexRoute: typeof ShellProfileIndexRoute
  ShellQuestionBankIndexRoute: typeof ShellQuestionBankIndexRoute
  ShellQuestionsIndexRoute: typeof ShellQuestionsIndexRoute
  ShellQuizzesIndexRoute: typeof ShellQuizzesIndexRoute
  ShellSubthemesIndexRoute: typeof ShellSubthemesIndexRoute
  ShellThemesIndexRoute: typeof ShellThemesIndexRoute
  ShellUsersIndexRoute: typeof ShellUsersIndexRoute
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellCalendarIndexRoute: ShellCalendarIndexRoute,
  ShellCategorysIndexRoute: ShellCategorysIndexRoute,
  ShellDashboardIndexRoute: ShellDashboardIndexRoute,
  ShellProfileIndexRoute: ShellProfileIndexRoute,
  ShellQuestionBankIndexRoute: ShellQuestionBankIndexRoute,
  ShellQuestionsIndexRoute: ShellQuestionsIndexRoute,
  ShellQuizzesIndexRoute: ShellQuizzesIndexRoute,
  ShellSubthemesIndexRoute: ShellSubthemesIndexRoute,
  ShellThemesIndexRoute: ShellThemesIndexRoute,
  ShellUsersIndexRoute: ShellUsersIndexRoute,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRouteRoute: ShellRouteRouteWithChildren,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignOutIndexRoute: authSignOutIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
